# Generated by Django 5.0 on 2024-01-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_alter_listings_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
            preserve_default=False,
        ),
    ]
