# Generated by Django 5.0 on 2024-01-02 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_listings_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 2, 3, 57, 57, 270798)
            ),
            preserve_default=False,
        ),
    ]
