# Generated by Django 5.0 on 2024-01-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_listings_bid_counter_alter_listings_date_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watchlist", to="auctions.listings"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="watchlist_counter",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
