# Generated by Django 5.0 on 2024-01-03 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_alter_bids_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bids",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bidder",
                to="auctions.listings",
            ),
        ),
        migrations.AlterField(
            model_name="bids",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
