# Generated by Django 5.0 on 2024-01-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0010_alter_bids_item_alter_bids_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="winner",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
