# Generated by Django 5.0 on 2024-01-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0012_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="comment",
            field=models.TextField(blank=True),
        ),
    ]
