# Generated by Django 5.0 on 2024-01-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0013_alter_comments_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="starting_bid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="listings",
            name="price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11),
        ),
    ]
