# Generated by Django 5.0 on 2024-01-11 00:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_user_following"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="likes",
            new_name="like_count",
        ),
        migrations.AddField(
            model_name="user",
            name="liked",
            field=models.ManyToManyField(
                blank=True, related_name="liker", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
