# Generated by Django 5.0 on 2024-01-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_rename_likes_post_like_count_user_liked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="liked",
            field=models.ManyToManyField(
                blank=True, related_name="liker", to="network.post"
            ),
        ),
    ]
